version: '3.1'

services:
  db:
    image: postgres:16.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: golang_news_bot
      PGDATA: /var/lib/postgresql/data/
      ports:
        -5432:5432
      volumes:
        -db:/var/lib/postgresql/data/

volumes:
  db: